<?php
/**
 * @file
 * Install, update, and uninstall functions for the Taxonomy Set Lineage module.
 */

/**
 * Convert Drupal variables to Backdrop config.
 */
function taxonomy_set_lineage_update_1000() {
  config_set('taxonomy_set_lineage.settings', 'vocabularies', update_variable_get('taxonomy_set_lineage_affected_taxonomies', array()));
  update_variable_del('taxonomy_set_lineage_affected_taxonomies');
}
